# vim: set sw=2 ts=2 et:

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_cmd = 'EasyAlign'
hook_add = '''
  vnoremap <silent> <Enter> :EasyAlign<Enter>
'''

[[plugins]]
repo = 'vim-scripts/textobj-rubyblock'
on_ft = 'ruby'

# autocomplete required in ruby
[[plugins]]
repo = 'ujihisa/neco-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
hook_add = '''
  let g:vim_json_syntax_conceal = 0
'''

[[plugins]]
repo = 'neoclide/jsonc.vim'
on_ft = 'jsonc'

[[plugins]]
repo = 'google/vim-jsonnet'
on_ft = 'jsonnet'

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
on_ft = 'dockerfile'

[[plugins]]
repo = 'osyo-manga/vim-over'
on_cmd = 'OverCommandLine'

# expand ruby matchit
[[plugins]]
repo = 'yasuoza/ruby-matchit'

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = 'markdown'
hook_add = '''
  let g:markdown_syntax_conceal = 0
'''

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee', 'markdown']

[[plugins]]
repo = 'slim-template/vim-slim.git'
on_ft = ['slim', 'markdown']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = 'go'
hook_add = '''
  let g:goimports_simplify = 1
'''
hook_post_update = '''
  call system('GO111MODULE=on go get -u golang.org/x/tools/gopls@latest')
  call system('GO111MODULE=on go get -u golang.org/x/tools/cmd/goimports@latest')
'''

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'javascriptreact']

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'
on_ft = ['typescript', 'typescriptreact']
hook_add = '''
  highlight link typescriptFuncName Title
'''

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = ['javascriptreact', 'typescriptreact']

[[plugins]]
repo = 'mattn/vim-sqlfmt'
on_ft = 'sql'
build = 'pip3 install --upgrade sqlparse'

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = 'terraform'
