# vim: set sw=2 ts=2 et:

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_cmd = 'EasyAlign'

[[plugins]]
repo = 'vim-scripts/textobj-rubyblock'
on_ft = 'ruby'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
hook_add = '''
  let g:vim_json_syntax_conceal = 0
'''

[[plugins]]
repo = 'google/vim-jsonnet'
on_ft = 'jsonnet'
merge_ftdetect = true

[[plugins]]
repo = 'gutenye/json5.vim'
on_ft = 'json5'
merge_ftdetect = true

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
on_ft = 'dockerfile'

[[plugins]]
repo = 'osyo-manga/vim-over'
on_cmd = 'OverCommandLine'

# expand ruby matchit
[[plugins]]
repo = 'yasuoza/ruby-matchit'

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = 'markdown'
hook_add = '''
  let g:markdown_syntax_conceal = 0
'''

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee', 'markdown']

[[plugins]]
repo = 'slim-template/vim-slim.git'
on_ft = ['slim', 'markdown']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = 'go'
hook_add = '''
  let g:goimports_simplify = 1
'''
hook_post_update = '''
  call system('go install golang.org/x/tools/gopls@latest')
  call system('go install golang.org/x/tools/cmd/goimports@latest')
'''

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'javascriptreact']

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'
on_ft = ['typescript', 'typescriptreact']
hook_add = '''
  highlight link typescriptFuncName Title
'''

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = ['javascriptreact', 'typescriptreact']

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = 'terraform'
hook_add = '''
  let g:terraform_fmt_on_save = 1
'''

[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = 'graphql'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'mattn/vim-gist'
on_cmd = 'Gist'
depends = ['webapi-vim']
hook_add = '''
  let g:gist_clip_command = 'pbcopy'

  let g:gist_list_vsplit = 1
  let g:gist_detect_filetype = 1

  let g:gist_show_privates = 1
  let g:gist_get_multiplefile = 1

  let g:gist_post_private = 1
  let g:gist_open_browser_after_post = 1
'''
