# vim: set sw=2 ts=2 et:

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_cmd = 'EasyAlign'

[[plugins]]
repo = 'vim-scripts/textobj-rubyblock'
on_ft = 'ruby'

# autocomplete required in ruby
[[plugins]]
repo = 'ujihisa/neco-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
hook_add = '''
  let g:vim_json_syntax_conceal = 0
'''

[[plugins]]
repo = 'neoclide/jsonc.vim'
on_ft = 'jsonc'

[[plugins]]
repo = 'google/vim-jsonnet'
on_ft = 'jsonnet'

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
on_ft = 'dockerfile'

[[plugins]]
repo = 'osyo-manga/vim-over'
on_cmd = 'OverCommandLine'

# expand ruby matchit
[[plugins]]
repo = 'yasuoza/ruby-matchit'

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = 'markdown'
hook_add = '''
  let g:markdown_syntax_conceal = 0
'''

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee', 'markdown']

[[plugins]]
repo = 'slim-template/vim-slim.git'
on_ft = ['slim', 'markdown']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = '''
  " Syntax Highlight
  let g:go_highlight_functions = 1
  let g:go_highlight_methods = 1
  let g:go_highlight_fields = 1
  let g:go_highlight_types = 1
  let g:go_highlight_operators = 1
  let g:go_highlight_build_constraints = 1

  " Faster update
  let g:go_updatetime = 0

  " Use coc-go for autocomplete
  let g:go_def_mapping_enabled = 0

  " Use coc-go for completion
  let g:go_code_completion_enabled = 0

  " Floating window for GoDoc
  let g:go_doc_popup_window = 1

  " gofmt + goimports on save
  let g:go_fmt_command = "goimports"

  " Silent errors
  let g:go_fmt_fail_silently = 1
  let g:go_list_height = 0
  let g:go_highlight_diagnostic_errors = 0
  let g:go_highlight_diagnostic_warnings = 0
'''

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'javascriptreact']

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'
on_ft = ['typescript', 'typescriptreact']
hook_add = '''
  highlight link typescriptFuncName Title
'''

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = ['javascriptreact', 'typescriptreact']

[[plugins]]
repo = 'mattn/vim-sqlfmt'
on_ft = 'sql'
build = 'pip3 install --upgrade sqlparse'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
on_cmd = ['VimFiler', 'VimFilerCurrentDir', 'VimFilerBufferDir', 'VimFilerSplit', 'VimFilerExplorer', 'VimFilerDouble']
on_path = '.*'

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = 'terraform'
