os:
  copyToClipboardCmd: "printf {{text}} | pbcopy"

gui:
  # If true, show a random tip in the command log when Lazygit starts
  showRandomTip: false

  # If true, show the command log
  showCommandLog: false

  # Enable nerd font icons
  nerdFontsVersion: "3"

# Keybindings
keybinding:
  universal:
    prevBlock-alt: <c-k>
    nextBlock-alt: <c-j>
    executeShellCommand: '!'
    prevPage: <c-u>
    nextPage: <c-d>

  commits:
    moveDownCommit: ''
    moveUpCommit: ''
