[[plugins]]
repo = 'junegunn/vim-easy-align'
on_cmd = 'EasyAlign'

[[plugins]]
repo = 'vim-scripts/textobj-rubyblock'
on_ft = 'ruby'

# autocomplete required in ruby
[[plugins]]
repo = 'ujihisa/neco-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'osyo-manga/vim-over'
on_cmd = 'OverCommandLine'

# expand ruby matchit
[[plugins]]
repo = 'yasuoza/ruby-matchit'

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = 'javascript'

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = 'markdown'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee', 'markdown']

[[plugins]]
repo = 'slim-template/vim-slim.git'
on_ft = ['slim', 'markdown']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = 'javascript'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = ['Denite', 'DeniteCursorWord']
hook_post_source = '''
  call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
'''
[[plugins]]
repo = 'Shougo/vimfiler.vim'
on_cmd = ['VimFiler', 'VimFilerCurrentDir', 'VimFilerBufferDir', 'VimFilerSplit', 'VimFilerExplorer', 'VimFilerDouble']
on_path = '.*'

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = 'terraform'
