#!/usr/bin/env bash

# Verbose output
set -x

RUBY_VER='2.2.3'

# Develop requirements
sudo apt-get update
sudo apt-get install -y python-software-properties python g++ make curl
sudo add-apt-repository -y ppa:git-core/ppa
sudo add-apt-repository -y ppa:chris-lea/node.js
sudo add-apt-repository -y ppa:mercurial-ppa/releases
sudo apt-get update
sudo apt-get install -y git language-pack-en zsh nodejs

# Vim
cd /tmp && hg clone https://github.com/vim/vim.git && cd vim
sudo apt-get install -y build-essential gettext libncurses5-dev luajit lua5.2 liblua5.2-dev python-dev python3-dev ruby-dev libperl-dev tcl-dev
./configure            \
--with-features=huge   \
--enable-multibyte     \
--enable-rubyinterp    \
--enable-pythoninterp  \
--enable-python3interp \
--enable-luainterp     \
--with-lua-prefix=/usr \
--enable-perlinterp    \
--enable-tclinterp     \
--enable-cscope        \
--enable-fontset
make
sudo make install

# zsh
git clone --recursive https://github.com/yasuoza/dotfiles.git ~/dotfiles && \
cd ~/dotfiles && make install                                            && \
sudo chsh -s `which zsh` `whoami`

# Ruby
sudo apt-get install -y --force-yes zlib1g-dev libssl-dev libreadline-dev libyaml-dev libxml2-dev libxslt-dev
git clone https://github.com/sstephenson/rbenv.git $HOME/.rbenv                                     && \
git clone https://github.com/sstephenson/ruby-build.git $HOME/.rbenv/plugins/ruby-build             && \
git clone https://github.com/sstephenson/rbenv-gem-rehash.git $HOME/.rbenv/plugins/rbenv-gem-rehash && \
$HOME/.rbenv/bin/rbenv install $RUBY_VER                                                            && \
$HOME/.rbenv/bin/rbenv global  $RUBY_VER
