#!/usr/bin/env bash

DOTFILES_DIR=$(cd $(dirname $(dirname $0));pwd)
DOTFILES=$(find $(dirname $(dirname $0)) -maxdepth 1 -type f  -name .\*                   \
           ! \( -name "*vim*" -o -name "*zsh*" -o -name "*git*" -o -name ".travis.yml" \) \
           | sed 's/^\.\///')

function setup () {
    clean

		mkdir -p $HOME/.config

    for file in ${DOTFILES[@]}
    do
        ln -s {$DOTFILES_DIR,$HOME}/$file
    done

    ln -s $DOTFILES_DIR/bin $HOME/.bin
}

function clean () {
    for file in ${DOTFILES[@]}
    do
        rm -f $HOME/$file
    done

    rm -rf $HOME/.bin
}

function usage () {
    echo "setup: symlink dotfiles"
    echo "clean: cleanup dotfiles"
}

if [ -z $1 ]; then
  usage
  exit 1
fi

while [ "$1" != "" ]; do
    case "$1" in
        setup | install )       setup
                                exit
                                ;;
        clean | uninstall )     clean
                                exit
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done
