#!/usr/bin/env bash

DOTFILES_DIR=`cd $(dirname $(dirname $0));pwd`

function setup () {
    ln -s $DOTFILES_DIR/vim/init.vim $HOME/.vimrc

    mkdir -p $HOME/.vim
    ln -s $DOTFILES_DIR/vim/coc-settings.json $HOME/.vim/coc-settings.json

    mkdir -p $HOME/.vim/bundle/repos/github.com/Shougo/dein.vim
    git clone --depth 1 https://github.com/Shougo/dein.vim  $HOME/.cache/dein/repos/github.com/Shougo/dein.vim
}

function update () {
    echo "Launch vim and :call dein#update()"
}

function clean () {
    rm -rf $HOME/.vimrc
    rm -rf $HOME/.vim
}

function usage () {
    echo "setup: symlink .vimrc and install bundles"
    echo "clean: cleanup .vimrc and .vim"
}

if [ -z $1 ]; then
  usage
  exit 1
fi

while [ "$1" != "" ]; do
    case "$1" in
        setup | install )       setup
                                exit
                                ;;
        update )                update
                                exit
                                ;;
        clean | uninstall )     clean
                                exit
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done
