#!/usr/bin/env bash

DOTFILES_DIR=`cd $(dirname $(dirname $0));pwd`

function setup () {
    ln -s $DOTFILES_DIR/.vimrc $HOME/.vimrc

    pip3 install --force-reinstall --user neovim
    mkdir -p $HOME/.config/nvim
    ln -s $DOTFILES_DIR/nvim/init.vim $HOME/.config/nvim/init.vim

    mkdir -p $HOME/.vim/bundle/repos/github.com/Shougo/dein.vim
    git clone https://github.com/Shougo/dein.vim  $HOME/.vim/bundle/repos/github.com/Shougo/dein.vim
}

function update () {
    echo "Launch vim and :call dein#update()"
}

function clean () {
    rm -rf $HOME/.vimrc
    rm -rf $HOME/.vim
}

function usage () {
    echo "setup: symlink .vimrc and install bundles"
    echo "clean: cleanup .vimrc and .vim"
}

if [ -z $1 ]; then
  usage
  exit 1
fi

while [ "$1" != "" ]; do
    case "$1" in
        setup | install )       setup
                                exit
                                ;;
        update )                update
                                exit
                                ;;
        clean | uninstall )     clean
                                exit
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done
