#!/usr/bin/env bash

DOTFILES_DIR=`cd $(dirname $(dirname $0));pwd`

function setup () {
    ln -sf $DOTFILES_DIR/vim/init.vim $HOME/.vimrc

    pip3 install --force-reinstall --user pynvim
    mkdir -p $HOME/.config/nvim
    ln -sf $DOTFILES_DIR/vim/* $HOME/.config/nvim

    git clone --depth 1 https://github.com/Shougo/dein.vim  $HOME/.cache/nvim/dein
}

function update () {
    echo "Launch vim and :call dein#update()"
}

function clean () {
    rm -rf $HOME/.config/nvim
    rm -rf $HOME/.vimrc
    rm -rf $HOME/.vim
    rm -rf $HOME/.cache/nvim
}

function usage () {
    echo "setup: symlink .vimrc and install bundles"
    echo "clean: cleanup .vimrc and .vim"
}

if [ -z $1 ]; then
  usage
  exit 1
fi

while [ "$1" != "" ]; do
    case "$1" in
        setup | install )       setup
                                exit
                                ;;
        update )                update
                                exit
                                ;;
        clean | uninstall )     clean
                                exit
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done
