#!/usr/bin/env bash

DOTFILES_DIR=$(cd $(dirname $(dirname $0));pwd)

function setup () {
    clean
    ln -s $DOTFILES_DIR/.zshrc $HOME/.zshrc
    ln -s $DOTFILES_DIR/.zshenv $HOME/.zshenv
}

function clean () {
    rm -f $HOME/.zshrc
    rm -f $HOME/.zshenv
}

function usage () {
    echo "setup: symlink .zshrc(s)"
    echo "clean: remove .zshrc(s)"
}

if [ -z $1 ]; then
  usage
  exit 1
fi

while [ "$1" != "" ]; do
    case "$1" in
        setup | install )       setup
                                exit
                                ;;
        clean | uninstall )     clean
                                exit
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done
