#!/usr/bin/env bash

DOTFILES_DIR=$(cd $(dirname $(dirname $0));pwd)

function setup () {
    clean
    ln -s $DOTFILES_DIR/.zshrc $HOME/.zshrc
}

function clean () {
    rm -f $HOME/.zshrc
}

function usage () {
    echo "setup: symlink .zshrc"
    echo "clean: remove .zshrc"
}

if [ -z $1 ]; then
  usage
  exit 1
fi

while [ "$1" != "" ]; do
    case "$1" in
        setup | install )       setup
                                exit
                                ;;
        clean | uninstall )     clean
                                exit
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done
