name: Docker build and push
on:
  push:
  schedule:
    - cron:  '0 20 * * *' # 05:00 JST

jobs:
  build:
    name: docker build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build image
        run: |
          if [ ${{ github.ref }} = 'refs/heads/master' ]; then
            IMAGE_TAG='latest'
          else
            IMAGE_TAG=$(echo ${{ github.ref }} | sed -E 's#refs/(tags|heads)/##g')
          fi
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          docker build . -t ${{ github.repository }}:$IMAGE_TAG
      - name: Login to Docker Hub
        env:
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
          DOCKER_HUB_PASS: ${{ secrets.DOCKER_HUB_PASS }}
        run: docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
      - name: Push Docker Hub
        run: |
          docker push ${{ github.repository }}:$IMAGE_TAG
