name: Docker build and push
on:
  push:
    branches:
      - main

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    strategy:
      matrix:
        distro:
          - debian
          - distro: debian
            platforms: >-
              linux/amd64,
              linux/arm64/v8,

    name: docker build and push
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.4

      - name: Setup QEMU user-mode emulation
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.distro }}-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.distro }}-${{ github.ref }}
            ${{ runner.os }}-buildx-${{ matrix.distro }}-
            refs/head/main

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ matrix.platforms }}
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ github.repository }}:latest
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
